# mariadb/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-db-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.rootUser.password | b64enc }}
  mysql-user: {{ .Values.db.user | b64enc }}
  mysql-password: {{ .Values.db.password | b64enc }}
