name: Build and Deploy Application

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_ADMIN_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_ADMIN_USERNAME }} --password-stdin

    - name: Build and push MediaWiki image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/mediawiki:latest ./mediawiki
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mediawiki:latest

    - name: Build and push MariaDB image
      run: |
        docker build --build-arg MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }} -t ${{ secrets.ACR_LOGIN_SERVER }}/mariadb:latest ./mariadb
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/mariadb:latest

  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # - name: Set up Azure CLI
    #   uses: azure/CLI@v1

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group mediawiki-rg --name mediawiki-aks

    - name: Deploy MariaDB
      run: |
        helm upgrade --install mariadb ./mariadb/chart \
          --set rootUser.password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          --set db.user=${{ secrets.MYSQL_USER }} \
          --set db.password=${{ secrets.MYSQL_PASSWORD }} \
          --set db.name=${{ vars.MYSQL_DATABASE }}

    - name: Deploy MediaWiki
      run: |
        helm upgrade --install mediawiki ./mediawiki/chart \
          --set externalDatabase.password=${{ secrets.MYSQL_PASSWORD }}
