name: Deploy Mediawiki Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group mediawiki-rg --name mediawiki-aks

    - name: Generate Docker config JSON
      id: docker_config
      run: |
        DOCKER_CONFIG_JSON=$(echo -n "{\"auths\":{\"mediawikideployacr01.azurecr.io\":{\"username\":\"${{ secrets.ACR_ADMIN_USERNAME }}\",\"password\":\"${{ secrets.ACR_ADMIN_PASSWORD }}\",\"email\":\"\"}}}")
        $(echo -n "{\"auths\":{\"mediawikideployacr01.azurecr.io\":{\"username\":\"${{ secrets.ACR_ADMIN_USERNAME }}\",\"password\":\"${{ secrets.ACR_ADMIN_PASSWORD }}\",\"email\":\"\"}}}")
        $(echo -n "{\"auths\":{\"mediawikideployacr01.azurecr.io\":{\"username\":\"${{ secrets.ACR_ADMIN_USERNAME }}\",\"password\":\"$ACR_PASSWORD\",\"email\":\"\"}}}" | base64 -w 0)
        echo "DOCKER_CONFIG_JSON=$DOCKER_CONFIG_JSON" >> $GITHUB_ENV

    - name: Deploy ACR Secret
      run: |
        helm upgrade --install common ./common/chart --set acr.dockerconfigjson=${{ env.DOCKER_CONFIG_JSON }}

    - name: Deploy MariaDB
      run: |
        helm upgrade --install mariadb ./mariadb/chart \
          --set rootUser.password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          --set db.user=${{ secrets.MYSQL_USER }} \
          --set db.password=${{ secrets.MYSQL_PASSWORD }} \
          --set db.name=${{ vars.MYSQL_DATABASE }}

    - name: Deploy MediaWiki
      run: |
        helm upgrade --install mediawiki ./mediawiki/chart \
          --set externalDatabase.password=${{ secrets.MYSQL_PASSWORD }}
